# Generated by Django 4.2.2 on 2023-06-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_subscriptions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='IngredientInRecipe',
        ),
    ]
