# Generated by Django 4.2.2 on 2023-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredientrecipe_ingredientinrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=7, unique=True, verbose_name='Цвет в HEX'),
            preserve_default=False,
        ),
    ]
